# 使用基础镜像
FROM node:16-alpine

# 设置工作目录
WORKDIR /usr/src/app

# 将依赖文件复制到工作目录
COPY package*.json ./

# 安装依赖
RUN npm install

# 将服务器代码复制到工作目录
COPY . .

# 暴露端口
EXPOSE 3000

# 启动服务器
CMD ["npm", "start"]
